Set wshShell = wscript.CreateObject("WScript.Shell")
do
wscript.sleep 20000
wshshell.sendkeys "{CAPSLOCK}"
wscript.sleep 30000
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 100
wshshell.sendkeys "{SCROLLOCK}"
wscript.sleep 15
wshshell.sendkeys "{PAUSEBREAK}"
wscript.sleep 111
wshshell.sendkeys "{INSERT}"
wscript.sleep 400
wshshell.sendkeys "{HOME}"
wscript.sleep 500
wshshell.sendkeys "{PAGEUP}"
wscript.sleep 50
wshshell.sendkeys "{PAGEDOWN}"
wscript.sleep 100
wshshell.sendkeys "{DELETE}"
wscript.sleep 150
wshshell.sendkeys "{PRINTSCREENSYSRQ}"
wscript.sleep 200
wshshell.sendkeys "{NUMLOCK}"
wscript.sleep 1000
wshshell.sendkeys "{TAB}"
wscript.sleep 300
wshshell.sendkeys "{SHIFT}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
wshshell.sendkeys "{DELETE}"
loop
